### ISSUE TITLE
Wrong API key?

### ISSUE THREAD

**Issue by macedonga** [michelangelomo/Classeviva-Official-Endpoints#11]
When I make a request to `https://web.spaggiari.eu/rest/v1/auth/login` with the correct headers and the correct data i get:
`{ "statusCode": 400, "error": "204:CvvRestApi\/apikey not matching" }`

Any help?

**Comment by Simoneu01** [comment]
How are you making the request?
I just tried and everything works correctly

**Comment by macedonga** [comment]
Yes,
I am using the correct headers:
`User-Agent: zorro/1.0`
`Z-Dev-Apikey: +zorro+`
`Content-Type: application/json`

And the right data:
` {"ident": null, "pass": "password", "uid": "username"} `

**Comment by Simoneu01** [comment]
try removing "ident" from the data.

Let me know if you are Italian

**Comment by macedonga** [comment]
Ok, ho provato a rimuovere "ident" ed adesso mi dice:
![image](https://user-images.githubusercontent.com/19750900/99380277-05c16f80-28ca-11eb-9c93-a51f527e00e9.png)

**Comment by Simoneu01** [comment]
Che programma stai usando? Se stai facendo tu che linguaggio di programmazione stai usando?

Io avevo fatto uno script python e funzionava. Stessa cosa ora sto provando con Insomnia / Postman e mi torna i dati richiesti.

Ti metto lo screenshot di quello che metto per sicurezza.

![image](https://user-images.githubusercontent.com/43807696/99389196-f563c180-28d6-11eb-81d6-bc85b770508f.png)

![image](https://user-images.githubusercontent.com/43807696/99389233-ff85c000-28d6-11eb-9843-f08bc1cc9496.png)

**Comment by macedonga** [comment]
Sto usando la libreria RestSharp (C#) per fare le richieste, ma ho provato anche con Postman e mi da sempre lo stesso errore.
```C#
var client = new RestClient("https://web.spaggiari.eu/rest/v1/");

var request = new RestRequest("auth/login", DataFormat.Json);
request.AddHeader("Content-Type", "application/json");
request.AddHeader("Z-Dev-Apikey", "+zorro+");
request.AddHeader("User-Agent", "zorro/1.0");
ClasseVivaLogin login = new ClasseVivaLogin
{
   uid = Username.Text,
   pass = Password.Text
};

request.AddParameter("application/json; charset=utf-8", JsonConvert.SerializeObject(login), ParameterType.RequestBody);
request.RequestFormat = DataFormat.Json;

var response = client.Post(request);
MessageBox.Show(response.Content);
```

Questo è il mio codice.

**Comment by macedonga** [comment]
Uhm, ho riprovato senza modificare niente ed adesso funziona con Postman...
Non so cosa sia successo...

**Comment by macedonga** [comment]
Allora è un problema con il mio codice.
Chiudo questo problema. Scusate

**Comment by Simoneu01** [comment]
Ok nice

**Comment by macedonga** [comment]
Ok, in caso serva a qualcuno ecco il codice che funziona
```C#
var client = new RestClient("https://web.spaggiari.eu/rest/v1/auth/login");
client.Timeout = -1;
var request = new RestRequest(Method.POST);
client.UserAgent = "zorro/1.0";
request.AddHeader("Z-Dev-Apikey", "+zorro+");
request.AddHeader("Content-Type", "application/json");

ClasseVivaLogin login = new ClasseVivaLogin
{
    uid = Username.Text,
    pass = Password.Text
};

request.AddParameter("application/json", JsonConvert.SerializeObject(login), ParameterType.RequestBody);
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
```

Ed ecco la classe che uso per fare il JSON (ma si potrebbe anche subito fare in una stringa)
```C#
class ClasseVivaLogin
{
    public string uid;
    public string pass;
}
```

Ah, e grazie mille @Simoneu01
