### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by DevNull-00** [michelangelomo/Classeviva-Official-Endpoints#3]
I'm just trying to get a response from 'rest/v1/auth/login' but, even with the correct headers:
- User-Agent: zorro/1.0
- Z-Dev-Apikey: +zorro+

And the correct body:
`{"ident":null","pass":"my_pass","uid":"my_uid"}`

It still gives me this error: 
```
statusCode:400
error:"202:CvvRestApi/apikey request header not found: Z-Dev-Apikey"
```

**Comment by michelangelomo** [comment]
Can't replicate.
Please verify headers. Headers are case-sensitive.

Anyway it's "Z-Dev-ApiKey", not "Z-Dev-Apikey" (the k is uppercase)

**Comment by michelangelomo** [comment]
Can't replicate. Please verify headers, it works for me.

![schermata 2019-01-03 alle 12 34 19](https://user-images.githubusercontent.com/3934987/50635847-242b5580-0f54-11e9-8817-a0eef5b58843.png)

**Comment by DevNull-00** [comment]
Ok, update, I got a different response this time, it says
`{"statusCode":400,"error":"101:CvvRestApi\/invalid payload"}`
Are you sure that the body key "ident" has to stay to null?
And how can I get my userId? On the website, I log-in with my email, but in the request the email doesn't work

**Comment by michelangelomo** [comment]
Invalid payload means body not correct. Please be sure that you are sending JSON as body payload

**Comment by DevNull-00** [comment]
I got the auth/login working, but if I try to use other methods it always gives me this error:
`{"statusCode":404,"error":"254:CvvRestApi\/not authorized","message":"student-id is incompatible with auth-token"}`
![immagine](https://user-images.githubusercontent.com/43378701/50638089-ba637980-0f5c-11e9-99a3-0c3c4693ca9d.png)

I've tried to change the auth-token but I still get the same error

**Comment by michelangelomo** [comment]
In login response you get an **ident** like _S26432R_.
Take this value, remove all letters and use it as student-id

**Comment by DevNull-00** [comment]
Thank you I think I almost got it, but what {subject} value is required in {student_id}/grades/subject/{subject}?
I've tried with subjectId, subjectCode and subjectDesc, but it doesn't work

**Comment by michelangelomo** [comment]
Sorry, I can't help you. This project is unmaintained.

**Comment by michelangelomo** [comment]
Please open new issues if you have another questions.

**Comment by Simoneu01** [comment]
> Thank you I think I almost got it, but what {subject} value is required in {student_id}/grades/subject/{subject}?
> I've tried with subjectId, subjectCode and subjectDesc, but it doesn't work

Per caso sei riuscito a far funzionare questo endpoint?
@ItzLuk3
