### ISSUE TITLE
Endpoint /notes/type/{type}/read/{note} not working

### ISSUE THREAD

**Issue by DevNull-00** [michelangelomo/Classeviva-Official-Endpoints#4]
I don't know if it's me or something else, but this endpoint is not working.
Is the URL correct? And if it is, what do you mean with the parameter {note}? Is it the evtId or something else?
URL I'm trying: `https://web.spaggiari.eu/rest/v1/students/695****/notes/type/NTTE/read/16193***`
Response that I get: `{"statusCode":404,"error":"102:CvvRestApi\/wrong uri"}`

**Comment by michelangelomo** [comment]
Okay, I've checked the issue and I've updated the documentation.

**Please refer to https://github.com/michelangelomo/Classeviva-Official-Endpoints/commit/a726a73ad8b5af85a6e275a133932be9a46b0428**
