### ISSUE TITLE
Endpoint Docenti

### ISSUE THREAD

**Issue by Knocks83** [michelangelomo/Classeviva-Official-Endpoints#5]
What about the Docenti endpoints?

**Comment by michelangelomo** [comment]
I don't have access to Docenti environment.
APK can be decompiled to extract endpoints but I can't test it 🤷

**Comment by DevNull-00** [comment]
I think I found the endpoints you are looking for.
https://drive.google.com/open?id=1JOrlshfW-HXg4xv0P47y2JcILoALh21P <--- this is the file where the magic happens
https://drive.google.com/open?id=1X8rwsu9jN1cqGT22hViksnWTIM0N6-ZX <--- this is all the decompiled apk if you wanted to take a look to some other files.
I just used [http://www.javadecompilers.com](url) for the apk and grepWin for a global search into the files.
Hope that helps :)
##### EDIT
I also don't have access to docenti environment, so I could not test the endpoints, but I found them in the last version of 'Classeviva Docenti' APK, so I think they do work

**Comment by Knocks83** [comment]
Ok, thanks a lot! When I'll have the time I'll check them (but if you took them from the official app I think they will work).

**Comment by michelangelomo** [comment]
This endpoints might be unstable, I don't trust Spaggiari at all 🙃

**Comment by not-eexto** [comment]
Ciao ragazzi, ho trovato un piccolo spunto per gli endpoints dei docenti e dei genitori ai link [https://web.spaggiari.eu/rest/v1/teachers/](https://web.spaggiari.eu/rest/v1/teachers/) & [https://web.spaggiari.eu/rest/v1/parents/](https://web.spaggiari.eu/rest/v1/parents/)

Infatti questi link danno errore 400 perchè non sono autenticato ma non danno errore 404. Ci sarebbe da trovare qualcuno che ne sappia un po' di più, o magari contattare qualcuno dentro a Spaggiari. @michelangelomo @ItzLuk3 @simonesestito

**Comment by DevNull-00** [comment]
Ciao, @xenud 
Gli endpoint studenti e genitori sono quasi identici (cambiano solo dei privilegi per la visualizzazione di comunicazioni e pagelle), facendo delle prove ho visto che è possibile accedere con delle credenziali genitore all'endpoint studente, ma non ho provato viceversa appunto perché non ne sapevo dell'esistenza.
Riguardo all'endpoint docenti, è rozzo, incompleto e instabile, ed inoltre mi servirebbero delle credenziali da docente per accedervi, quindi non ho potuto sperimentare, ma non ne vale quasi la pena.
Ho il sospetto che con delle credenziali di privilegi maggiori (presidenza scolastica, ecc.) si possa entrare anche nella fascia amministrativa dell'istituto tramite l'endpoint docenti.

**Comment by not-eexto** [comment]
> Ho il sospetto che con delle credenziali di privilegi maggiori (presidenza scolastica, ecc.) si possa entrare anche nella fascia amministrativa dell'istituto tramite l'endpoint docenti.

Si molto probabile, intanto vi allego una lista di tutti gli endpoint dei docenti e degli studenti che ho trovato.
<details>
  <summary>ENDPOINT AGGIORNATI AL 19/06/2019</summary>

```
rest/v1/auth/_zsid
rest/v1/auth/login
rest/v1/auth/ticket
rest/v1/parents/{studentId}/talks/book/{teacherId}/{frameId}/{bitmask}
rest/v1/parents/{studentId}/talks/delete/{talkId}
rest/v1/parents/{studentId}/talks/teachersframes2/{begin}/{end}
rest/v1/students/{studentId}/_options
rest/v1/students/{studentId}/absences/details
rest/v1/students/{studentId}/absences/details/{begin}
rest/v1/students/{studentId}/absences/details/{begin}/{end}
rest/v1/students/{studentId}/agenda/all/{begin}/{end}
rest/v1/students/{studentId}/agenda/{eventCode}/{begin}/{end}
rest/v1/students/{studentId}/calendar/all
rest/v1/students/{studentId}/card
rest/v1/students/{studentId}/cards
rest/v1/students/{studentId}/didactics
rest/v1/students/{studentId}/didactics/item/{contentId}
rest/v1/students/{studentId}/documents
rest/v1/students/{studentId}/documents/check/{hash}
rest/v1/students/{studentId}/documents/read/{hash}
rest/v1/students/{studentId}/grades2
rest/v1/students/{studentId}/lessons/today
rest/v1/students/{studentId}/lessons/{day}
rest/v1/students/{studentId}/lessons/{start}/{end}
rest/v1/students/{studentId}/notes/all/
rest/v1/students/{studentId}/notes/{type}/read/{note}
rest/v1/students/{studentId}/noticeboard
rest/v1/students/{studentId}/noticeboard/attach/{eventCode}/{pubId}/{numOfFile}
rest/v1/students/{studentId}/noticeboard/read/{eventCode}/{pubId}/101
rest/v1/students/{studentId}/periods
rest/v1/students/{studentId}/subjects
rest/v1/teachers/{teacherId}/_options
rest/v1/teachers/{teacherId}/_st/lessontypes
rest/v1/teachers/{teacherId}/_st/sctelessontypes
rest/v1/teachers/{teacherId}/agenda/all/{classType}/{classId}/{start}/{end}
rest/v1/teachers/{teacherId}/agenda/mine/{start}/{end}
rest/v1/teachers/{teacherId}/card
rest/v1/teachers/{teacherId}/cards
rest/v1/teachers/{teacherId}/classes/all/students1
rest/v1/teachers/{teacherId}/classes/extracurricola/students1
rest/v1/teachers/{teacherId}/classes/mine/students1
rest/v1/teachers/{teacherId}/didactics/addfile/{folderId}
rest/v1/teachers/{teacherId}/didactics/addfolder
rest/v1/teachers/{teacherId}/didactics/additem/{folderId}
rest/v1/teachers/{teacherId}/didactics/any
rest/v1/teachers/{teacherId}/didactics/attachfolder/{folderId}
rest/v1/teachers/{teacherId}/didactics/attachitem/{contentId}
rest/v1/teachers/{teacherId}/didactics/deletefolder/{folderId}
rest/v1/teachers/{teacherId}/didactics/deleteitem/{itemId}
rest/v1/teachers/{teacherId}/didactics/item/{contentId}
rest/v1/teachers/{teacherId}/didactics/sharefolder/{folderId}
rest/v1/teachers/{teacherId}/didactics/shareitem/{itemId}
rest/v1/teachers/{teacherId}/didactics/unsharefolder/{folderId}
rest/v1/teachers/{teacherId}/didactics/unshareitem/{itemId}
rest/v1/teachers/{teacherId}/evaluations/components/{classType}/{classId}/{subjectId}
rest/v1/teachers/{teacherId}/evaluations/grades2
rest/v1/teachers/{teacherId}/evaluations/grades2/mine
rest/v1/teachers/{teacherId}/evaluations/grades2/{classType}/{classId}/{subjectId}
rest/v1/teachers/{teacherId}/evaluations/skills/{classType}/{classId}/{subjectId}
rest/v1/teachers/{teacherId}/lessons/mine/{begin}/{end}
rest/v1/teachers/{teacherId}/lessons/students/{classType}/{classId}
rest/v1/teachers/{teacherId}/lessons/students/{classType}/{classId}/{date}
rest/v1/teachers/{teacherId}/lessons/students/{classType}/{classId}/{start}/{end}
rest/v1/teachers/{teacherId}/notes/day/{classType}/{classId}/{day}
rest/v1/teachers/{teacherId}/notes/mine/{begin}/{end}
rest/v1/teachers/{teacherId}/notes/range/{classType}/{classId}/{begin}/{end}
rest/v1/teachers/{teacherId}/noticeboard
rest/v1/teachers/{teacherId}/noticeboard/attach/{eventCode}/{pubId}/{numOfFile}
rest/v1/teachers/{teacherId}/noticeboard/read/{eventCode}/{pubId}/101
rest/v1/teachers/{teacherId}/students/pendingevents/{classType}/{classId}
rest/v1/teachers/{teacherId}/students/status/{classType}/{classId}/{day}
rest/v1/teachers/{teacherId}/subjects/list/{classType}/{classId}
rest/v1/teachers/{teacherId}/teachers

```
</details>

Ora vedo se trovo un professore disponibile a sperimentare o addirittura provare a contattare ClasseViva per chiedere la documentazione... Nel caso vi faccio sapere
