### ISSUE TITLE
Voti per materia

### ISSUE THREAD

**Issue by Simoneu01** [michelangelomo/Classeviva-Official-Endpoints#8]
Salve a tutti.

Quando provo ad fare una richiesta all'endpoint:
`{student_id}/grades/subject/{subject}`
mi ritorna questo errore:
`{
    "error": "102:CvvRestApi/wrong uri", 
    "statusCode": 404
}`

Ho provato a sostituire `{subject}` con `subjectId`, `subjectCode `e `subjectDesc `ma continua a non funzionare.

Qualcuno ha una soluzione?

**Comment by DevNull-00** [comment]
Grazie della segnalazione, dopo aver controllato mi sono accorto che l'endpoint di cui stai parlando è deprecato. Verrà rimosso al più presto dalla documentazione
